[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$jtYN/6uF$ZPl1DrYCTZvAiH7ftw2pS1"
  ]
[http.routers.api]
  rule = "Host(`console.localhost.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"